### ISSUE TITLE
Problem with RSS feed

### ISSUE THREAD

**Issue by travisdowns** [travisdowns/travisdowns.github.io#1]
User CPC reports by email that images (and to some extent tables) are broken in the [RSS feed](https://travisdowns.github.io/feed.xml).

All of the URLs seem to be missing the domain part, like:

```
<link href="/blog/2019/03/19/random-writes-and-microcode-oh-my.html" rel="alternate" type="text/html" title="What has your microcode done for you lately?"/>
```

Probably Jekyll config needs to be updated to specify the domain.

**Comment by cpitclaudel** [comment]
Fixed! Thanks a lot. And it also fixes the image problem, since apparently Thunderbird has trouble fetching them with relative URLs (?)

**Comment by travisdowns** [comment]
Great!

I think the problem was that for relative URLs to work the feed still has to indicate somewhere what the base URL is (for http this is implied by the http document the link appears in), since the location of the feed.xml doens't necessarily have any relationship to the resources it is referring to - and the way I had it configured the feed.xml didn't have the base URL _anywhere_.

Apparently some readers like inoreader will handle this by interpreting any relative URLs relative to the feed document location, but that's probably a workaround for buggy feeds.
