### ISSUE TITLE
SVG circles renders wrong on WebKit

### ISSUE THREAD

**Issue by travisdowns** [travisdowns/travisdowns.github.io#102]
[Per HN](https://news.ycombinator.com/item?id=23230047):

> Sadly not related to the content itself, but WebKit browsers seem to misrender your indicator circles in the third graph :(
> Desktop and mobile Safari both do it. Firefox shows the circles in a reasonable place.

**Comment by saagarjha** [comment]
Here's how it looks like in Safari:

<img width="1392" alt="Screen Shot 2020-05-18 at 18 21 35" src="https://user-images.githubusercontent.com/13786931/82274231-6c25ff00-9934-11ea-942f-f8ae3c4c19d2.png">

I assume Firefox is doing it right:

<img width="1392" alt="Screen Shot 2020-05-18 at 18 22 22" src="https://user-images.githubusercontent.com/13786931/82274271-87910a00-9934-11ea-8f21-1c8c97b512f8.png">

**Comment by travisdowns** [comment]
@saagarjha thanks so much! Yes, Firefox has it right (not surprisingly, as that's what I tried it on :)).

Should have a fix shortly.

**Comment by travisdowns** [comment]
Same problem in GNOME web, great:

![image](https://user-images.githubusercontent.com/2403521/82274480-40b00e00-994e-11ea-92be-d78a568ce196.png)


I kind of knew I'd regret hand-coding this SVG overlay...

**Comment by travisdowns** [comment]
Yes, the issue is that WebKit doesn't seem to honor the center transform set on a parent element:

~~~
<style>
.svg-center-xfrm * {
  transform-box: fill-box;
  transform-origin: center;
}
</style>

<div class="img-overlay-wrap">
  <img class="figimg" src="{{assetpath}}/fig7a.svg" alt="Figure 7a Annotated">
  <svg viewBox="0 0 90 60">
    <g class="svg-center-xfrm" stroke-width=".5" fill="none" opacity="0.5">
      <ellipse transform="rotate(-25 34 10)" cx="34" cy="10" rx="12" ry="5" stroke="green" />
      <ellipse transform="rotate(-25 34 34.5)" cx="34" cy="34.5" rx="12" ry="5" stroke="red" />
    </g>
  </svg>
</div>
~~~

svg-center-xfrm wasn't taking effect on the two ellipses.

**Comment by travisdowns** [comment]
@saagarjha - should be working now, give it a shot if you can!

https://travisdowns.github.io/blog/2020/05/18/icelake-zero-opt.html?foo=jsdjl

Note the foo=kljsdj to break the caching GH pages does.

**Comment by travisdowns** [comment]
Should be fixed in d15ab71b2eb451d1f792ab32594f2e8fd0fab4be.

![image](https://user-images.githubusercontent.com/2403521/82274986-a51f9d00-994f-11ea-81ae-38c3dcad5f30.png)

**Comment by saagarjha** [comment]
Yes, it looks fixed to me too. Thanks!

**Comment by travisdowns** [comment]
Great, credited in the next push:

![image](https://user-images.githubusercontent.com/2403521/82276039-2f690080-9952-11ea-86bb-f0bf83b86113.png)

LMK if for some reason you wish to remain anonymous.
