### ISSUE TITLE
Two typos in "Gathering Intel on Intel AVX-512"

### ISSUE THREAD

**Issue by jlebar** [travisdowns/travisdowns.github.io#11]
Loved the post.  Found two typos:

* "Checking whether the voltage-only transition implied by a 256-bit instructions"
* The "Voltage Effects" header is very tiny, smaller than regular text, presumably that is not WAI.

**Comment by travisdowns** [comment]
>     * "Checking whether the voltage-only transition implied by a 256-bit instructions"

Thanks, fixed and credited (LMK if you don't want to be credited for some reason) in next push.



>     * The "Voltage Effects" header is very tiny, smaller than regular text, presumably that is not WAI.

Well it is not WAI in the sense that I don't want it to be really small, but it is WAI in the sense that I intend for it to be at the heading level it is at (`h5`), i.e., a subheading of "voltage only transitions" section. I don't know why browsers would render `h5` as smaller than regular text but I am certainly not an HTML expert, or even an informed novice.

For now I'll just remove it has a heading and bold it maybe (but then it won't appear in the TOC).

Thanks for your comment!
