### ISSUE TITLE
Switch to invisible reCAPTCHA for comment form

### ISSUE THREAD

**Issue by techboyg5** [travisdowns/travisdowns.github.io#166]
I'm pretty sure it's easy, but let's experiment with the invisible reCAPTCHA and Staticman.

**Comment by travisdowns** [comment]
@techboyg5 - indeed, when I added reCAPTCHA, I saw this option (the v3 version), but went with v2 out of familiarity. I like this idea, not least because the reCAPTCHA element is the widest thing (by min width) in the layout so on small mobile screens it extends to the right beyond the rest of the content, which is not nice.

Are there any downsides to the invisible reCAPTCHA? If the person isn't trusted by whatever magic the invisible version uses, how does it verify them in that case?

**Comment by techboyg5** [comment]
> 
> 
> @techboyg5 - indeed, when I added reCAPTCHA, I saw this option (the v3 version), but went with v2 out of familiarity. I like this idea, not least because the reCAPTCHA element is the widest thing (by min width) in the layout so on small mobile screens it extends to the right beyond the rest of the content, which is not nice.
> 
> Are there any downsides to the invisible reCAPTCHA? If the person isn't trusted by whatever magic the invisible version uses, how does it verify them in that case?

**v3 and invisible are different things.** I want the **v2 Invisible** reCAPTCHA, **not v3**.
| Thing | Checkbox | Invisible | v3 |
| --- | --- | --- | --- |
| Checkbox | Yes | No | No |
| Challenge| Yes | Yes | No |

**Comment by travisdowns** [comment]
@techboyg5 - thanks for the clarification. So v2 invisible. Do you know what's the benefit of v2 invisible over v3? I guess the fallback is nice. 

I have seen very little spam, but I can't say if it's reCAPTCHA, or the honeypot field or what. I'm also thinking it would be nice if staticman could whitelist email addresses that were seen before (e.g., if the repo has a comment already with the same email hash, or maybe based on a "whitelist this" comment on the merge request).

**Comment by techboyg5** [comment]
> 
> 
> @techboyg5 - thanks for the clarification. So v2 invisible. Do you know what's the benefit of v2 invisible over v3? I guess the fallback is nice.
> 
> I have seen very little spam, but I can't say if it's reCAPTCHA, or the honeypot field or what. I'm also thinking it would be nice if staticman could whitelist email addresses that were seen before (e.g., if the repo has a comment already with the same email hash, or maybe based on a "whitelist this" comment on the merge request).

v2 invisible is better because it has a fallback, as you and I said.

**Comment by travisdowns** [comment]
@techboyg5 - I ended up disabling reCAPTCHA as a test, and I haven't seen any increase in spam at all. Maybe reCAPTCHA was pointless all along?

**Comment by travisdowns** [comment]
Closed b/c I was able to disable reCAPTCHA entirely.
