### ISSUE TITLE
ssh key generation with correct format

### ISSUE THREAD

**Issue by willymcallister** [travisdowns/travisdowns.github.io#26]
In blog post travisdowns.github.io/_posts/2020-02-05-now-with-comments.md
change the ssh-key command 
from:
ssh-keygen -t rsa -b 4096 -C "staticman key" -f ~/.ssh/staticman_key

to:
ssh-keygen -m PEM -t rsa -b 4096 -C "staticman key" -f ~/.ssh/staticman_key

**Comment by travisdowns** [comment]
Fixed and added a check to make sure you got an RSA key:

![image](https://user-images.githubusercontent.com/2403521/75499000-af587d80-5996-11ea-87dc-dd51718d7e79.png)
