### ISSUE TITLE
ASM syntax highlighting on Blogs

### ISSUE THREAD

**Issue by gamozolabs** [travisdowns/travisdowns.github.io#3]
Just a heads up that you can do

```
```nasm
```

To get x86 assembly (nasm flavor) syntax highlighting on assembly snippits in your blogs :)

**Comment by travisdowns** [comment]
What!? I swear I tried that (and ~~~nasm). Let me check again...

**Comment by gamozolabs** [comment]
Ah I see. It _kindof_ works? But not for many instructions. Works in the Github preview though, lame. Seems to bold common x86 instructions but not many of the SIMD ones.

**Comment by travisdowns** [comment]
The preview for markdown like these issues?

```nasm
mov eax, eax
add eax, 1
pshufb xmm0, xmm0, xmm0
vpshufb xmm0, xmm0, xmm0
foo eax,eax
```

Huh, yeah.

**Comment by travisdowns** [comment]
Man the style for assembly is kind of ugly with my theme though, the `[` and `]` come out looking red like they are a syntax error or something:

![image](https://user-images.githubusercontent.com/2403521/59310491-24025500-8c6c-11e9-8b54-5c71631fda04.png)

**Comment by gamozolabs** [comment]
Yeah... shame it's not as clean as it could be. Sorry for opening the issue. Hopefully the highlighting will get better over time (or maybe I'll look into what a PR takes for w/e does the formatting). I use a lot of asm in my blogs as well, it's nice to have :P

**Comment by travisdowns** [comment]
@gamozolabs - no apologies needed, I am happy you mentioned it or I never would have figured it out.

I think the style comes from the CSS embedded in the theme and it can be overridden I guess (blogging is making me learn more about Jekyll and CSS than I really wanted, but maybe it's a good thing?).

**Comment by travisdowns** [comment]
This one seems solved, although I'm still looking into how to make the colors less yucky:

https://stackoverflow.com/questions/56552943/changing-code-sample-format-for-nasm-code-samples-in-jekyll

**Comment by travisdowns** [comment]
The underlying issue is [this one](https://github.com/rouge-ruby/rouge/issues/1310) in the rouge highlighter: the nasm lexer is very limited and when it barfs (e.g., on any indexed addressing mode), it shows up with that red error highlight. That one is moving slowly, so for now a workaround is just to override the error style in the css to do nothing (I can live with my blog syntax highlighter not flagging my errors) as discussed in #9 .

So I think I can close this one now.
