### ISSUE TITLE
LSD expansion

### ISSUE THREAD

**Issue by Smattr** [travisdowns/travisdowns.github.io#7]
The glossary expands LSD as

> [LSD]: Loop stream decoder

For Intel, LSD actually expands to "Loop Stream *Detector*" (§2.4.2.4 of the optimization guide). I didn't submit a PR to change this, because maybe the discrepancy here is intentional? Maybe you are using LSD to describe a more generic hypothetical unit that could be decoding a specific loop instruction?

**Comment by travisdowns** [comment]
@Smattr  - no I was trying to describe the detector :), I guess I just wasn't aware of the proper name. Fixing...
